Hello hello hello, Your looking at this to donate to the Player Project, right? 
The Player Project is a open-source TV database made by Iconicx® and our project needs funding with the help... of you.
New donations will come soon.
